### ISSUE TITLE
Improve templates: make links easier to edit

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/data-ethics-club#109]
Templates (particularly the meeting template) could be made much more usable by using the style of markdown links where you just have to put in each link once at the bottom (see [here](https://raw.githubusercontent.com/alan-turing-institute/the-turing-way/main/CONTRIBUTING.md) for example.

- [x] Edit `meeting-template.md`
- [x] Check if other templates could be improved in this manner

**Comment by ninadicara** [comment]
I've had a look and for now I'm not sure there are other templates that we use regularly that could be improved in this way - HackMD only seems to allow use of reference-style links for internal linking to other HackMD documents which is annoying! Thats the only other doc I would think this is useful for. Closing for now :)
