### ISSUE TITLE
Links in readme result in Page 404

### ISSUE THREAD

**Issue by annaledwoch** [very-good-science/data-ethics-club#112]
The following links in the readme file return `404: Page not Found`:

`https://very-good-science.github.io/data-ethics-club/contents/meetings/next-meeting.html`
`https://very-good-science.github.io/data-ethics-club/contents/administration.html`
`https://very-good-science.github.io/data-ethics-club/contents/code-of-conduct.html`

I think that the navigation on Data Ethics Club website has changed.

**Comment by ninadicara** [comment]
Thanks so much @annaledwoch ! I'll fix those now 😁
