### ISSUE TITLE
Decide first (few) things to read/watch/etc

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/data-ethics-club#14]
- [x] Decide what to read/watch
- [x] Add these to the 'upcoming meeting dates' markdown doc @ninadicara 
- [x] Add a document each in 'meetings' 
  - [x] 20/01 @NatalieThurlby (27/11/21)
  - [x] 03/02 @ninadicara  (20/01/21)

**Comment by ninadicara** [comment]
Done!
