### ISSUE TITLE
Tasks to do over summer

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-ethics-club#141]
A big ol' list of all the things we haven't quite got around to or would like to do over the summer break when we don't have meetings on. 

- [x] Add all current suggestions to the reading list #121, #131, #134 - @ninadicara
  - [x] Also add the things from the Data Hazards slack 
  - [x] https://2022.internethealthreport.org/episodes/
  - [x] https://kevinguyan.com/writing/
- [x] Tick off things we've read on the reading List - @ninadicara 
- [ ] Start to... #145 
- [x] Any new contributors?
- [ ] #157 
- [ ] Try implementing the new categorisation for the website #158 #146 
- [ ] Send out new recruitment emails ahead of next block to departments at other universities, industry etc to reach some new attendees, and also see if anyone new wanted to get involved in organising. This probably incorporates both...
     - [ ] #85 
     - [x] #140 
- [ ] Survey of current DEC mailing list people - can use Mailchimp to do an embedded survey. It would be good to know if people have ideas for different types of events or would suggest changes to the format.
- [ ] #223
- [ ] New dates! - @NatalieZelenka

**Comment by HDiscoDay** [comment]
Can we add blog stuff. Happy to take point on organising people to write blogs. 
If we want to just add them like we do writeups then I can handle that.
If we want to add a new section to add those writeups then I can not do that :')
Lemme know

**Comment by NatalieZelenka** [comment]
Okay, I'm promoting "blog" to it's own issue and then closing this one!
