### ISSUE TITLE
Custom JS for Reading List organisation

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-ethics-club#146]
It would be really nice if we could enhance the organisation of the reading list by allowing pieces to have multiple tags, and for people to filter based on these. 
Currently we fit them into sections because we need a way to organise them, but in reality lots of them have multiple possible themes which would be cool to reflect. 

This would require some custom code to fit alongside the Sphinx theme etc. 

@bengcooper reckons he might be able to do this for us so putting this as an issue/reminder to self.

**Comment by NatalieZelenka** [comment]
This issue describes a solution that isn't the one we're going for in the end. See PR #218 for what we landed on.
