### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-ethics-club#15]
A CoC for the discussion space. 
Examples: 
[Turing Way](https://github.com/alan-turing-institute/the-turing-way/blob/master/CODE_OF_CONDUCT.md#4-enforcement-manual)
[Diversity Journal Club @ Arizona](https://www.as.arizona.edu/diversity_coffee/#two)
[Carpentries](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html)
[Social Rules](https://www.recurse.com/manual#sub-sec-social-rules)
JGI

- [x] Discuss potential content (inc. how can people report incidents?)
- [x] Prepare draft on repo (@ninadicara )
- [x] Agree version for first meeting (@NatalieThurlby and @ninadicara)

**Comment by NatalieThurlby** [comment]
Yes, good idea. The JGI recently made one so maybe we could also look at that. One thing that we need to remember to think about is how people can report incidents.

**Comment by ninadicara** [comment]
Good plan! Added

**Comment by ninadicara** [comment]
CoC amended following suggestions in our meeting on 13.01.2021 and merged into the main branch :)
