### ISSUE TITLE
Reading list categorisation

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-ethics-club#158]
We are currently having an ongoing discussion as the maintainers of the website about how we should categorise the reading list items going forwards. 
We're working on a multi-class categorisation option to improve our current one!

I was also thinking that we could add some accessibility tags. 
So, if it's an audio recording, does it have a transcript available?
If it's a video, does it have closed-captioning?

**Comment by NatalieZelenka** [comment]
Some ideas here that relate to #218 - @ninadicara to review?
