### ISSUE TITLE
[SUGGESTION(S)] Role of Mathematics - suggested by Susana

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-ethics-club#159]
Thanks for making a suggestion!

- [x] Add: http://mujaawarah.org/en/2021/03/09/the-role-of-mathematics-in-the-destruction-of-communities-and-what-we-can-do-to-reverse-this-process-including-using-mathematics/?fbclid=IwAR3vqmt1qOemXHqYWZHpEhOb-6aQPVvTyzQYNVWOAdYG6n_7pt-jR8OcuUo
- [x] Add Susana as a contributor (Susana465)

For each suggestion, please let us know:
* The name of the content
* The type of content (paper/blog/video, etc)
    * Is it a preprint? 
    * Is it very long? If so, do you have a recommended section?
* A link where it can be accessed
* Any particular questions or points for discussion
* Are you happy to be credited for providing this recommendation in our contributors section?

**Comment by ninadicara** [comment]
https://github.com/Susana465
