### ISSUE TITLE
[SUGGESTION(S)] Patient and public involvement to build trust in artificial intelligence: a framework, tools and case studies

### ISSUE THREAD

**Issue by neelsoumya** [very-good-science/data-ethics-club#167]
Patient and public involvement to build trust in artificial intelligence: a framework, tools and case studies

https://www.cell.com/patterns/fulltext/S2666-3899(22)00098-8

Thanks for making a suggestion!

For each suggestion, please let us know:
* The name of the content

Patient and public involvement to build trust in artificial intelligence: a framework, tools and case studies

* The type of content (paper/blog/video, etc)

Journal   

* A link where it can be accessed

https://www.cell.com/patterns/fulltext/S2666-3899(22)00098-8

* Any particular questions or points for discussion

How to involve stakeholders (like patients) in AI reearch

* Are you happy to be credited for providing this recommendation in our contributors section?

Yes

**Comment by ninadicara** [comment]
Thank you for suggesting this (and writing it!) - I've actually had it printed out to read for a little while so it would be a great one to discuss :) I'm going to put it in the suggestion batch for our first set of meetings back in September.

**Comment by neelsoumya** [comment]
Thank you so much @ninadicara ! please send me your feedback/suggestions about the paper. I would love to have your feedback on it!
