### ISSUE TITLE
The Data Scientists' Oath?

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-ethics-club#2]
Title: The Financial Modelers Manifesto
Type: 2 page doc, easy read. 
Link: https://www.uio.no/studier/emner/sv/oekonomi/ECON4135/h09/undervisningsmateriale/FinancialModelersManifesto.pdf

I feel like this is a good jumping off point for conversations about...
- What would a data scientists' hippocratic oath look like? especially in behavioural research! 
- Who should hold research data science to account?
(There might be stuff on this already, feel free to ignore if so!)

**Comment by NatalieThurlby** [comment]
Thanks Nina! It's been added.

FYI, my plan is to close issues as I add them to the main list.

**Comment by NatalieThurlby** [comment]
I just found this: https://virginia-eubanks.com/2018/02/21/a-hippocratic-oath-for-data-science/ - relevant to the discussion! (By the author of automating inequality)
