### ISSUE TITLE
🍂 Autumn 2023 Organiser Tasks 🍂

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-ethics-club#221]
|                                                                                                                      | 8th Nov  | 22nd Nov | 8th Dec |
|---------------------------------------------------------------------|----------|-----------|---------|
| Read content, write questions and summary                                          |     Nat      |    Amy     |     Vanessa      |
| Website updates (create page, update join-in, update next-meeting) |     Nina      |  Nina        |     Nina   |
| Send reminder email                                                                                  |     Nina    |    Nina       |     Nina   |
| Choose vote options for next meeting                                                     |   Nina     |   Vanessa  |   Vanessa  |
| Set up HackMD                                                                                          |   Nina    |   Nat   |    Nina    |
| Write up meeting summary and add to website                                     |     Jess      |     Jess     |     Jess    |
| Proof read write up                                                                                    |  Vanessa   |    Amy    |       Huw     |

Huw will tweet if he remembers.

First meeting back in January will be New Years' Resolutions!

**Comment by ninadicara** [comment]
To edit the issue and add your name to a column, click the three dots in the top right of the issue box. 
Click `edit`.
Add your name in between the  `| |` that represent the cell you're trying to change. 
Click save. 

Message on Slack if you're stuck :)

**Comment by NatalieZelenka** [comment]
- [ ] Add links to how to do each of these tasks
- [ ] Review how well this worked as a system
