### ISSUE TITLE
Create an initial CSV file to populate the new airtable

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-ethics-club#222]
We have a new airtable and we would like to populate it with all our existing reading list!

It might be possible to write a little bit of code that goes from the [reading list markdown](https://dataethicsclub.com/_sources/reading-list.md.txt) to a first pass of a csv file that would go with our new [airtable spreadsheet](https://airtable.com/app1HHxlA2zZMlIPT/shr57ScyQg4EpdA5x/tblW9lzU64cMuKcft?backgroundColor=purple&layout=card&viewControls=on).

@vairylein to try to do this! 
@ninadicara to add any extra info that Vanessa might need to write this script.

From there, we can hopefully organise a working meeting where we can add more tags, link to past write-ups, etc.

**Comment by NatalieZelenka** [comment]
I think that @vairylein has now done this? Do we need to do anything else @ninadicara @vairylein before this issue is closed?

**Comment by vairylein** [comment]
Extracted info from the reading list markdown and added the things we read manually. (Some items are still missing some info e.g Author Name
