### ISSUE TITLE
[SUGGESTION(S)] Teaching coding inclusively: if this, then what?

### ISSUE THREAD

**Issue by Lextuga007** [very-good-science/data-ethics-club#233]
For each suggestion, please let us know:
* Teaching coding inclusively: if this, then what? 
* Paper is 9 pages long but very readable. No one section stands out.
* https://osf.io/preprints/socarxiv/3r2ez
* What is the impact on AI if women, feminised, or gender diverse people feel excluded in the sector to the point that, even when they succeed in the AI courses, they do not believe they know how to code?
* Yes I'm happy to be credited for providing the recommendation.

**Comment by ninadicara** [comment]
Added to the new (!) reading list - thanks Zoë!
