### ISSUE TITLE
🌻 DEC Spring Schedule 🌻 

### ISSUE THREAD

**Issue by HuwWDay** [very-good-science/data-ethics-club#252]
Need to organise a co-organiser meeting (probably online) to decide on sessions after Easter.

- [x] Decide on which dates we'll do/how long of an Easter break we'll have.
- [x] Fill out the table below
- [x] Who can help with data week talk?
- [x] Who can help with SWW DTP Summer Research Festival Talk? - @ninadicara will do this
- [x] A DEC meet up - summer picnic?
- [x] Announcing the new Slack channel

|                                                                               | 24th April | 8th May | 22nd May  | Tuesday 4th June (Data Week) | Wednesday 5th June (SWW DTP Summer Research Festival) |
|--------------------------------|----------|-----------|---------|----------|-----------|
| Read content, write questions and summary      |     ~~Huw~~    |  ~~Vanessa~~     |   ~~Amy~~       |   X    |      X   |
| [Website updates (create page, update join-in, update next-meeting)](https://dataethicsclub.com/how_to/meeting-todo-list.html#first) |  ~~Nina~~     |  ~~Vanessa~~   |  ~~Vanessa~~  |   Nina      |   X   | 
| Send reminder email and tweets                 |     ~~Huw~~  |     ~~Huw~~    |   ~~Huw~~       |    Huw       |    Huw |
| Choose vote options for next meeting        |  ~~Vanessa~~   | ~~Amy~~    |  X      |   X  |    X    |
| [Set up HackMD](https://dataethicsclub.com/how_to/howto-sync-hackmd.html)                                            |   ~~Nina~~  |    ~~Nina~~     |    Nina    |    Nina    | X  |
| Write up meeting summary and [add to website](https://dataethicsclub.com/how_to/howto-add-writeups.html)    |    ~~Jess~~   |    Jess   |   Jess  |    Jess   |  X |

- Proof reading writeups: Jess to tag everyone on finished writeups and then we all just muck in rather than assign them!
- Data Week: everyone can help find videos (Huw has also emailed Catherine), maybe ask people in Zoom. If you're interested in helping out let us know. Say something in the email.
-

**Comment by ninadicara** [comment]
Actions - 
- [ ] Send newsletter this week inc: new dates, invite to Slack and invite to help organise Data Week
