### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/data-ethics-club#29]
- [x] For organisers:
  - [x] How to add people using the all-contributors bot (with and without gh username).
  - [x] How/when to email the mailing list (perhaps we can keep a password in our Sharepoint?)
  - [x] How to run a meeting:
     - [x] Poll next choice of paper. 
     - [x] (IDEA) We could have a poll at the end where we ask everyone "Would you recommend this content to a friend?" and "Did this content provoke a good discussion?", then our past papers would be more useful for other people.
- [x] For participants:
  - [x] How to suggest reading materials
  - [x] How to become an organiser
  - [x] How to lead a reading group

**Comment by NatalieThurlby** [comment]
We might also want to take a look at this: https://github.com/DataKind-UK/data-ethics-book-club-in-a-box 
There might be some processes or content suggestions that we might want to use :)

**Comment by NatalieThurlby** [comment]
Idea: asking members to tweet the summary of their discussions at #DataEthicsClub

**Comment by ninadicara** [comment]
Assigning myself to this, as it's linked to the work I said I'd do on writing instructions for DEC
