### ISSUE TITLE
[SUGGESTION(S)] You suggestion(s) here

### ISSUE THREAD

**Issue by berenicestr** [very-good-science/data-ethics-club#34]
Thanks for making a suggestion!

For each suggestion, please let us know:
* The name of the content
* The type of content (paper/blog/video, etc)
    * Is it a preprint? 
    * Is it very long? If so, do you have a recommended section?
* A link where it can be accessed
* Any particular questions or points for discussion
* Are you happy to be credited for providing this recommendation in our contributors section?

**Comment by ninadicara** [comment]
Empty issue so I'll close this now, but do get in touch @berenicestr if you'd like to add a resource! :) We're happy to help with the issue system, or [over email](https://github.com/very-good-science/data-ethics-club#organisers). N
