### ISSUE TITLE
Set up HackMD syncing for paper reviews

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/data-ethics-club#37]
Set up HackMD syncing with:
- [ ] Try one paper review syncing with gh-pages?
- [ ] For paper reviews: a website linking them, like [this](https://hackmdio.github.io/docs-with-hackmd)
- [ ] Write instructions letting people know how to use it best
- [ ] Figure out if it's possible to update all-contributors automatically based on contributions

**Comment by NatalieThurlby** [comment]
Ideas:
- Sync to a `collaborative-writing` branch during active collaboration
- PR to `gh-pages` branch when finalised
- Then PULL from `gh-pages` version to HackMD and only allow comments.

**Comment by ninadicara** [comment]
@NatalieThurlby I'm closing this as we are now regularly using HackMD and I think we've figured this out - but do reopen if there's still things to do here!
