### ISSUE TITLE
Add contributors for material suggestors

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/data-ethics-club#4]
* Using something akin to the all-contributors guidelines

**Comment by ninadicara** [comment]
Will work on adding this to the repo 👍

**Comment by ninadicara** [comment]
@all-contributors please add NatalieThurlby for event organizing and ideas

**Comment by ninadicara** [comment]
@all-contributors please add ninadicara for event organizing and ideas

**Comment by ninadicara** [comment]
TODO: 
1. Decide on contributor type for suggesting reading/watching materials (content, or ideas?). 
2. Add those who have suggested content so far (if they are happy to be linked)

**Comment by NatalieThurlby** [comment]
Yay Nina great work!!

**Comment by NatalieThurlby** [comment]
@all-contributors please add NatalieThurlby for content

**Comment by NatalieThurlby** [comment]
@all-contributors please add NatalieThurlby and ninadicara for content

**Comment by NatalieThurlby** [comment]
@all-contributors please add ninadicara for content

**Comment by NatalieThurlby** [comment]
NOTE: We have learned that you have to ask all-contributors one person at a time.

**Comment by NatalieThurlby** [comment]
@all-contributors please add mtwest2718 for content

**Comment by NatalieThurlby** [comment]
@all-contributors please add @milliams for content

**Comment by NatalieThurlby** [comment]
When I added extra contributors with the bot, Valentina was deleted. I'm seeing if we can add non-GH contributors manually to the `.all-contributorsrc` file to prevent that happening.

**Comment by NatalieThurlby** [comment]
@all-contributors generate

(not sure this will work)

**Comment by NatalieThurlby** [comment]
@all-contributors please add @ninadicara for infrastructure

**Comment by NatalieThurlby** [comment]
Awesome this seems to have worked!
@ninadicara: FYI, when we add people as contributors from outside of GitHub, we need to edit the `.all-contributorsrc` file. There might be a better way of doing this, but I think we either need to add something else with all-contributors bot (to get it to remake the README) - or we need to use the all-contributors CLI `generate` command (which I haven't tried).

**Comment by NatalieThurlby** [comment]
Okay, this is a test
@all-contributors please add @NatalieThurlby for content

**Comment by NatalieThurlby** [comment]
@all-contributors please add @NatalieThurlby for content

(The idea behind this is actually to get it to add in Miranda)

**Comment by NatalieThurlby** [comment]
@all-contributors please add @NatalieThurlby  for content

**Comment by NatalieThurlby** [comment]
@all-contributors please add @edwinrobots for content
