### ISSUE TITLE
Data Ethics Club feedback

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/data-ethics-club#46]
Feedback from March 17th:

>   * In my room we got involved in a discussion on Q1 and didn't consider the other Qs until near the end, so it'd be helpful to consider other ways to capture the discussion that mean we think more holistically (maybe putting one space for notes after all the Qs, or encouraging us to read the Qs out at the start of the breakout, or something) (+1)
>   * Yes I agree with the suggestion above - it might be nice to have a general space - often the discussion deviates from the questions. Also, I found it a bit difficult to jump between all the questions and find the space for my group - if we keep the questions it might be good to have the main headings be groups and the sub headings as questions instead of the other way around.

**Comment by ninadicara** [comment]
Closing as I think the template we've been using now reflects this feedback :)
