### ISSUE TITLE
Choose dates

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/data-ethics-club#5]
- [x] Choose date(s) for first sessions
- [x] Decide how often we should meet
- [x] Update README/or a dates markdown doc @ninadicara 
- [x] Advertise - fill in the JGI comms sheet @NatalieThurlby + send to mailing list when set up #6

**Comment by ninadicara** [comment]
@ninadicara to make md document with dates

**Comment by ninadicara** [comment]
This this is all done now! 
- [x] Mailing list set up & advertised (90 subscribers)
- [x] Dates for first 'term' (up to Easter) published 
- [x] Repo up to date
