### ISSUE TITLE
Living in the Hidden Realm of AI

### ISSUE THREAD

**Issue by vairylein** [very-good-science/data-ethics-club#54]
I recommend [Living in the Hidden Realm of AI](https://news.techworkerscoalition.org/2021/03/09/issue-5/) from the Tech Worker's Coalition blog. It is a fairly quick read.

Some discussion ideas: How far down the pipeline should our ethical responsibility as Data Scientists reach? What are better ways of recognising the contributions of annotators who are crucial to the existence of clean data sets and the products based on these data sets? What are our future visions of labour in a world that is becoming more Data and AI centric?

Happy to be in the contributers page as Vanessa Hanschke

**Comment by ninadicara** [comment]
This is a great addition - it's an important issue we don't have a lot of content on yet. I'll add it the reading list today and we will put it up as a suggestion to vote on at the next meeting 👍
