### ISSUE TITLE
[SUGGESTION(S)] what an ancient lake in Nevada tells us about the tech industry

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/data-ethics-club#61]
This is an article about the role of lithium mining in AI: 
 https://www.fastcompany.com/90618225/what-an-ancient-lake-in-nevada-reveals-about-the-future-of-tech?partner=rss&utm_campaign=rss+fastcompany&utm_content=rss&utm_medium=feed&utm_source=rss

**Comment by ninadicara** [comment]
Added!
