### ISSUE TITLE
HackMD write ups

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-ethics-club#68]
There are some outstanding write ups to do from the HackMD docs of the last series of Data Ethics Club. 
They are: 
- [x] [We created poverty](https://hackmd.io/vOBHfyC3R-qCSGtHFWT5Hw) - Apr 28th
  - [x] Write @HDiscoDay  
  - [x] Add to website @NatalieThurlby 
- [x] [Critical perspectives on computer vision](https://hackmd.io/K2LJwZyATyi19kQ2ANJvhw) - May 12th
  - [x] Write @HDiscoDay  
  - [x] Add to website @NatalieThurlby 
- [x] [Living in the hidden realms of AI - a workers perspective](https://hackmd.io/6vfdwIgWRYSLDtM7rvivBw) - May 26th
  - [x] Write @HDiscoDay  
  - [x] Add to website @NatalieThurlby

**Comment by HDiscoDay** [comment]
Can someone link me to a writeup that's already done so I can see the style you want it in? :)

**Comment by ninadicara** [comment]
Yup! In the MEETINGS.MD file [here](https://github.com/very-good-science/data-ethics-club/blob/main/MEETINGS.md) you can see at the bottom for meetings we have already had there are some that say 'meeting summary' - these will link you out to the writeups for those meetings :)

**Comment by HDiscoDay** [comment]
Just finished up a writeup of Living in the hidden realms of AI - a workers perspective. I'm still getting a hang of the format of these and think it'll be much easier to do them promptly after the discussion as opposed to a few months in hindsight. Would be good if we can briefly chat today in the meeting about what exactly the goal is with the writeups. 

I've also made a good start on the computer vision writeup as well but there's a lot more notes so trying to get a coherent narrative in the writeup is proving a little difficult.

**Comment by HDiscoDay** [comment]
So the computer vision is mostly done. Other than the usual bit of formatting magic that needs to be done for it, there's an anecdote in quote marks from the notes which I don't know whether to leave in or not and the final section is essentially a list. If you want me to tidy it up then I can do it when I get back, but if you want to finish it so it's ready for next Wednesday then that's also completely fine :)

**Comment by NatalieThurlby** [comment]
Thanks Huw!

I'll try to get it finished if I can I think, but I might not have time.

I didn't see your other comment earlier but I think the aim is to capture some of the discussion for people who couldn't make it, e.g. people who the time doesn't work for. So they might have had time to read the piece or maybe not. Maybe they want to see if people agreed with them or if there were any cool points they didn't think of. That's my imaginary target audience.

@ninadicara do you agree/have anything to add?

**Comment by HDiscoDay** [comment]
This'll sound like the dumbest question ever by where do I get access to the HackMD for the previous session (the maths of crime)?

**Comment by NatalieThurlby** [comment]
Hi @HDiscoDay not stupid at all. Last week's is [here](https://hackmd.io/@data-ethics-club/14-07-21/edit). In general, you can find them by logging into [hackmd.io](hackmd.io) with the login details in the [Sharepoint](https://uob.sharepoint.com/:w:/r/teams/grp-ethicaldatascience/Shared%20Documents/HackMD.docx?d=wd6740dcb84c44319bb3342cf2950fa60&csf=1&web=1&e=7Og11Z).

**Comment by HDiscoDay** [comment]
@NatalieThurlby thank you! The first link "here" did work. I've finished my writeup of last week's discussion, was hoping to get it done before the email went out but work got the better of me. Am actually quite happy with how this one went, definitely easier to write a more recent discussion up, but of course would welcome feedback from you both.

The second link "hackmd.io" does not work for me :/ If it's easier for you to just post a link to the hackmd doc each fortnight then that works fine by me, but regardless I'm sure we'll figure something out.

Sidenote: discussion private spies next week will be surprisingly topical giving all the stuff going on with Pegasus atm!

**Comment by NatalieThurlby** [comment]
Hi @HDiscoDay, oops, I left off the https, the link should work now - I edited the earlier comment. Yeah it should be interesting!  Who were you hacking to know that this was about to happen when you suggested it 😉? I read the article the other day - looking forward to talking about it 😄

**Comment by ninadicara** [comment]
Hi both - I've updated all of these on the website now so you should be able to find them here! https://very-good-science.github.io/data-ethics-club/contents/write_ups/write-ups.html
Huw I did a proof read of each and made a few small changes to make some sentences flow better etc but nothing major! 
Let's do a run through of how to upload them with the writeup of last week's one at some point in the next week or so? :)
