### ISSUE TITLE
Decide how to run meetings

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/data-ethics-club#7]
Options:
* zoom-style, like reproducibiliTea
* In an datawrapper/etherpad like data viz book club (e.g. https://notes.datawrapper.de/p/bookclub-datafeminism)

Decision: Zoom for now! (@NatalieThurlby will set up meetings), maybe etherpad later (after first term).

**Comment by ninadicara** [comment]
Really love the datawrapper concept - not seen that before ! I had been wondering how easy general discussion on zoom might be, can be tricky for people to jump in?

**Comment by NatalieThurlby** [comment]
Yeah I think breakout rooms and the chat would be useful for sure if we went for zoom, but I think I might prefer the data wrapper idea too.
