### ISSUE TITLE
Update the Mailchimp template

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/data-ethics-club#80]
The Mailchimp template is from the last set of meetings. It contains:
- the wrong zoom link
- it doesn't include Huw on the sign off
- it doesn't link to the website

@ninadicara - I hope to fix this soon, but I leave this here as a warning on the off chance I don't fix it before you must send an email.

**Comment by ninadicara** [comment]
Hiya, 
I've updated the template with these things!
I've made a few minor changes to the layout and also have tried added a calendar object so anyone should be able to add the events to their calendar - we should test this though first! 
N

**Comment by NatalieThurlby** [comment]
Thanks Nina!

I don't think i understand the calendar object. Can you explain it to me sometime?

**Comment by NatalieThurlby** [comment]
Gonna close this anyway! If we want to do fancy calendar things maybe we can make a new issue for that?

**Comment by ninadicara** [comment]
Sounds good! It's already done, just need to check it works for someone other than me. I'll show you in our next meeting - it's just an .ics file. ✨
