### ISSUE TITLE
[SUGGESTION(S)] Ethics Creep

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/data-ethics-club#90]
This paper on [ethics creep](https://link.springer.com/article/10.1023/B:Quas.0000049239.15922.a3) seems like something that should spark interesting discussion, and might be an opportunity for us to be a little more critical.

**Comment by HDiscoDay** [comment]
Concern that if someone doesn't have access through a uni institution then we'd have to deal with that. Are we allowed to get a copy of the pdf and circulate it within the group?

**Comment by NatalieThurlby** [comment]
Good point Huw. I'll add it to the reading list, but I will make a note of the fact it's not open source.
